<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class GrupoStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'materia_sigla' => 'required|string|between:4,10|exists:App\Core\Models\Materia,sigla',
            'grupo_nombre' => 'required|string|between:2,20',
            'docente_id' => 'required|integer|exists:App\Core\Models\Docente,persona_id',
            'horarios_id' => 'required|array|min:1',
            'horarios_id.*' => 'required|integer|exists:App\Core\Models\Horario,id',
            'periodo_codigo' => 'required|integer|exists:App\Core\Models\Periodo,codigo'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
