<?php

namespace App\Http\Requests;

use App\Core\Repositories\DiaInterface;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class HorarioStoreRequest extends FormRequest implements DiaInterface
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'dia' => ['required', 'string', Rule::in($this->getDias())],
            'hora_inicio' => 'required|date_format:H:i',
            'hora_fin' => 'required|date_format:H:i'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function getDias()
    {
        return [
            self::LUNES,
            self::MARTES,
            self::MIERCOLES,
            self::JUEVES,
            self::VIERNES,
            self::SABADO,
            self::DOMINGO
        ];
    }
}
