<?php

namespace App\Http\Requests;

use App\Core\Repositories\EstadoInterface;
use App\Core\Repositories\EstadoTrait;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class InstrumentoUpdateRequest extends FormRequest
{

    /**
     * traits
     */
    use EstadoTrait;

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nombreInstrumento_id' => 'required|integer|exists:App\Core\Models\NombreInstrumento,id',
            'estado' => ['required', 'string', Rule::in($this->getEstados())],
            'precio' => 'required|numeric|between:1,50000',
            'almacen_codigo' => 'required|integer|exists:App\Core\Models\Almacen,codigo',
            'compra_numero' => 'required|integer|exists:App\Core\Models\Compra,numero'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
