<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class MateriaStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'sigla' => 'required|string|between:4,10|unique:App\Core\Models\Materia,sigla',
            'nombre' => 'required|string|between:4,40',
            'precio' => 'required|numeric|between:1,5000',
            'cursos_codigos' => 'required|array|min:1',
            'cursos_codigos.*' => 'required|integer|exists:App\Core\Models\Curso,codigo',
            'promociones_id' => 'required|array|min:1',
            'promociones_id.*' => 'required|integer|exists:App\Core\Models\Promocion,id',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
