<?php

namespace App\Http\Requests;

use App\Core\Repositories\EstadoTrait;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class PrestamoUpdateRequest extends FormRequest
{

    /**
     * traits
     */
    use EstadoTrait;

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'encargadoDeAlmacen' => 'required|integer|exists:App\Core\Models\Adminstrativo,persona_id',
            'cliente' => 'required|integer|exists:App\Core\Models\Persona,id|',
            'instrumentos_id' => 'required|array|min:1',
            'instrumentos_id.*' => 'required|integer|exists:App\Core\Models\Instrumento.id',
            'estadoInstrumentos' => 'required|array|min:1',
            'estadoInstrumentos.*' => ['required', 'string', Rule::in($this->getEstados())]
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
