<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProveedorStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nombre' => 'required|string|between:3,50',
            'direccion' => 'required|string|between:4,100',
            'telefonos' => 'required|array|between:1,3',
            'telefonos.*' => 'required|integer|between:3000000,99999999|unique:App\Core\Models\Telefono,numero',
            'correo' => 'required|email|between:5,80|unique:App\Core\Models\Persona,correo',
            'ci_nit' => 'required|integer|digits_between:6,11|unique:App\Core\Models\Persona,ci_nit',
            'ciudad' => 'required|string|between:4,50'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
