<?php

namespace App\Http\Requests;

use App\Core\Repositories\EstadoInterface;
use App\Core\Repositories\EstadoTrait;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ReservaStoreRequest extends FormRequest implements EspecialidadRulesInterface
{
    /**
     * traits
     */
    use EstadoTrait;

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'check_reserva' => 'required|array|min:1',
            'check_reserva.*' => 'required|integer|exists:App\Core\Models\Instrumento,numero',
            'fecha' => 'required|date_format:Y-m-d',
            'hora' => 'required'
        ];
    }

    public function messages()
    {
        return[
            'fecha.required' => 'La :attribute es requerida',
            'fecha.date_format' => 'La :attribute debe tener el formato año/mes/día'
        ];
        //return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return
            ['fecha' => 'fecha de inicio'];
        //return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
