<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class VotosStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'mesa_recinto_id' => 'required|integer',
            'blanco' => 'required|integer',
            'nulo' => 'required|integer',

            'pre_mas' => 'required|integer',
            'dip_mas' => 'required|integer',

            'pre_cre' => 'required|integer',
            'dip_cre' => 'required|integer',

            'pre_com' => 'required|integer',
            'dip_com' => 'required|integer',

            'pre_adn' => 'required|integer',
            'dip_adn' => 'required|integer',

            'pre_fpv' => 'required|integer',
            'dip_fpv' => 'required|integer',

            'pre_pan' => 'required|integer',
            'dip_pan' => 'required|integer',

            'pre_lib' => 'required|integer',
            'dip_lib' => 'required|integer',

            'pre_jun' => 'required|integer',
            'dip_jun' => 'required|integer',


        ];
        /*  return [
              //
          ];*/
    }

    public function messages()
    {
        return [
            'blanco.required' => 'Rellene todos los campos',
            'nulo.required' => 'Rellene todos los campos',

            'pre_mas.required' => 'Rellene todos los campos',
            'dip_mas.required' => 'Rellene todos los campos',

            'pre_cre.required' => 'Rellene todos los campos',
            'dip_cre.required' => 'Rellene todos los campos',

            'pre_com.required' => 'Rellene todos los campos',
            'dip_com.required' => 'Rellene todos los campos',

            'pre_adn.required' => 'Rellene todos los campos',
            'dip_adn.required' => 'Rellene todos los campos',

            'pre_fpv.required' => 'Rellene todos los campos',
            'dip_fpv.required' => 'Rellene todos los campos',
            '
            pre_pan.required' => 'Rellene todos los campos',
            'dip_pan.required' => 'Rellene todos los campos',
            '
            pre_lib.required' => 'Rellene todos los campos',
            'dip_lib.required' => 'Rellene todos los campos',

            'pre_jun.required' => 'Rellene todos los campos',
            'dip_jun.required' => 'Rellene todos los campos',

        ];
        //return parent::messages(); // TODO: Change the autogenerated stub
    }

}
